a = figure('Position',[40 100 1100 500], ...
	'Tag','main_fig');
b = axes('Parent',a, ...
	'Box','on', ...
    'Units','normalized',...
	'Position',[0.08 0.1 0.8 0.8], ...
	'Tag','3D_HRTF');
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'Callback','cbi_3d_hrtf_l', ...
	'FontSize',10, ...
	'Position',[0.9 0.65 0.07 0.05], ...
	'String','LEFT EAR', ...
	'Tag','3D_HRTF_L');
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'Callback','cbi_3d_hrtf_r', ...
	'FontSize',10, ...
	'Position',[0.9 0.45 0.07 0.05], ...
	'String','RIGHT EAR', ...
	'Tag','3D_HRTF_R');
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'Callback','cbi_2d_hrtf_l', ...
	'FontSize',9, ...
	'Position',[0.9 0.59 0.07 0.05], ...
	'String','CURRENT ELEVTION', ...
	'Tag','2D_HRTF_L');
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'Callback','cbi_2d_hrtf_r', ...
	'FontSize',9, ...
	'Position',[0.9 0.39 0.07 0.05], ...
	'String','CURRENT ELEVTION', ...
	'Tag','2D_HRTF_R');